"""initial

Revision ID: 591f60fd9064
Revises: 
Create Date: 2025-11-08 20:27:09.831770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '591f60fd9064'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_docs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('nex_context_id', sa.String(), nullable=True),
    sa.Column('nex_context_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_docs_nex_context_id'), 'context_docs', ['nex_context_id'], unique=False)
    op.create_table('context_variants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('constraints_json', sa.JSON(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('parent_variant_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['context_docs.id'], ),
    sa.ForeignKeyConstraint(['parent_variant_id'], ['context_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_manifests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('TRAIN', 'EVAL', 'SYNTHETIC', 'FINETUNE_PACK', name='datasetkind'), nullable=False),
    sa.Column('context_id', sa.String(), nullable=True),
    sa.Column('variant_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('file_uris', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['context_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['context_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_vectors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['context_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id')
    )
    op.create_table('synthetic_examples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('example_type', sa.Enum('INSTRUCTION', 'QA', 'TASK', name='exampletype'), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('constraints_json', sa.JSON(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['context_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('underwriting_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('rubric_id', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('utility_score', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'HOLD', 'REJECT', name='underwritingdecision'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['context_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('example_id', sa.String(), nullable=False),
    sa.Column('y_text', sa.Text(), nullable=False),
    sa.Column('y_probs_json', sa.JSON(), nullable=True),
    sa.Column('y_scores_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['example_id'], ['synthetic_examples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('example_id')
    )
    op.create_table('teacher_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('example_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('usage_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['example_id'], ['synthetic_examples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_runs')
    op.drop_table('targets')
    op.drop_table('underwriting_runs')
    op.drop_table('synthetic_examples')
    op.drop_table('feature_vectors')
    op.drop_table('chunks')
    op.drop_table('dataset_manifests')
    op.drop_table('context_variants')
    op.drop_index(op.f('ix_context_docs_nex_context_id'), table_name='context_docs')
    op.drop_table('context_docs')
    # ### end Alembic commands ###

